import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../assets/globals.css"

import { ToastContainer } from "react-toastify";
import Sidebar from './../components/sidebar/index';
import Header from './../components/header/index';
import { links } from "@/utils/constants";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
      >
        <div className="flex min-h-screen overflow-hidden w-screen">
          <Sidebar links={links} />
          <div className="flex flex-col min-w-[450px] w-full">
            <Header />
            <main className="flex-1 bg-[#edeff9] text-black">{children}</main>
            <ToastContainer autoClose={500} />
          </div>
        </div>
      </body>
    </html>
  );
}
